[package]
name = "dll-injection-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build]
target = "x86_64-pc-windows-gnu"

[dependencies]

[dependencies.windows]
version = "0.57"
features = [
  "Foundation",
  "Win32",
  "Win32_UI",
  "Win32_UI_WindowsAndMessaging",
]
